# Generated by Django 3.1.3 on 2020-11-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя актера', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию актера', max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='photo/actors/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название постановки', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Введите описание постановки', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Репертуар',
                'verbose_name_plural': 'Репертуар',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='RepertoirePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Можете указать описание для фото (не более 200 символов) или оставить пустым', max_length=200, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photo/repertoire/', verbose_name='Фото')),
                ('repertoire', models.ForeignKey(help_text='Выбирете постановку из вашего репертуара', on_delete=django.db.models.deletion.CASCADE, to='teatr.repertoire', verbose_name='Постановка')),
            ],
            options={
                'verbose_name': 'Фотография постановки',
                'verbose_name_plural': 'Фотографии постановок',
            },
        ),
    ]
