# Generated by Django 3.1.3 on 2020-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['id'], 'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AddField(
            model_name='repertoire',
            name='poster',
            field=models.ImageField(blank=True, upload_to='photo/repertoire/', verbose_name='Постер'),
        ),
    ]
