# Generated by Django 3.1.3 on 2020-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0002_auto_20201118_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoire',
            name='poster',
            field=models.ImageField(upload_to='photo/repertoire/', verbose_name='Постер'),
        ),
    ]
