# Generated by Django 3.1.3 on 2020-11-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0003_auto_20201118_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repertoirephoto',
            old_name='photo',
            new_name='image',
        ),
    ]
