# Generated by Django 3.1.3 on 2020-11-20 08:01

from django.db import migrations, models
import teatr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0004_auto_20201118_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoirephoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=teatr.utils.repertoire_image_path, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='repertoirephoto',
            name='image',
            field=models.ImageField(upload_to=teatr.utils.repertoire_thumbnail_path, verbose_name='Фото'),
        ),
    ]
