# Generated by Django 3.1.3 on 2020-11-20 10:55

from django.db import migrations, models
import teatr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0006_auto_20201120_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoire',
            name='poster_thumbnail',
            field=models.ImageField(blank=True, upload_to=teatr.utils.repertoire_thumbnail_path, verbose_name='Миниатюра постера'),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='poster',
            field=models.ImageField(upload_to=teatr.utils.repertoire_image_path, verbose_name='Постер'),
        ),
    ]
