# Generated by Django 3.1.3 on 2020-11-20 11:57

from django.db import migrations, models
import teatr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0007_auto_20201120_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoire',
            name='poster',
            field=models.ImageField(max_length=250, upload_to=teatr.utils.repertoire_image_path, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='poster_thumbnail',
            field=models.ImageField(blank=True, max_length=250, upload_to=teatr.utils.repertoire_thumbnail_path, verbose_name='Миниатюра постера'),
        ),
        migrations.AlterField(
            model_name='repertoirephoto',
            name='image',
            field=models.ImageField(max_length=250, upload_to=teatr.utils.repertoire_image_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='repertoirephoto',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=250, upload_to=teatr.utils.repertoire_thumbnail_path, verbose_name='Миниатюра'),
        ),
    ]
