# Generated by Django 3.1.3 on 2020-11-20 12:38

from django.db import migrations, models
import teatr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0008_auto_20201120_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to=teatr.utils.actor_image_path, verbose_name='Фото'),
        ),
    ]
