# Generated by Django 3.1.3 on 2020-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatr', '0009_auto_20201120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoire',
            name='tmp_id',
            field=models.IntegerField(default=1471101, help_text='Введите номер события из Timepad', verbose_name='Идентификационный номер события на Timepad'),
            preserve_default=False,
        ),
    ]
