# Generated by Django 3.1.3 on 2020-12-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sendpulse_status',
            field=models.BooleanField(default=False, editable=None, verbose_name='Подключен к sendpulse'),
        ),
    ]
