# Generated by Django 3.1.3 on 2020-12-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_subscriber_sendpulse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='phone',
        ),
    ]
